"""Step 3: Fetch full text and evaluate papers via the Claude API.

Each candidate paper is:
  1. Full-text fetched (Europe PMC XML → publisher HTML → abstract-only fallback)
  2. Sent to Claude with the evaluation rubric
  3. Assessed via tool_use for structured output
"""

import json
import logging
import re
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import requests
from anthropic import Anthropic

from .config import get_config

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Full-text fetching
# ---------------------------------------------------------------------------

def _fetch_epmc_xml(pmcid: str) -> str | None:
    """Fetch full-text XML from Europe PMC (works for PMC open-access papers)."""
    if not pmcid:
        return None
    cfg = get_config()
    url = f"{cfg.api_endpoints.europepmc_fulltext}/{pmcid}/fullTextXML"
    try:
        resp = requests.get(url, timeout=cfg.timeouts.api_request)
        if resp.status_code == 200 and len(resp.text) > 1000:
            return resp.text
    except requests.RequestException:
        pass
    return None


def _fetch_publisher_html(doi: str) -> str | None:
    """Fetch HTML from the publisher via DOI redirect."""
    if not doi:
        return None
    cfg = get_config()
    url = f"https://doi.org/{doi}"
    try:
        resp = requests.get(
            url,
            headers={"Accept": "text/html", "User-Agent": "KosmosPipeline/1.0"},
            timeout=cfg.timeouts.api_request,
            allow_redirects=True,
        )
        if resp.status_code == 200 and len(resp.text) > 2000:
            # Strip script/style tags to reduce token count
            from bs4 import BeautifulSoup
            soup = BeautifulSoup(resp.text, "html.parser")
            for tag in soup(["script", "style", "nav", "footer", "header"]):
                tag.decompose()
            return soup.get_text(separator="\n", strip=True)
    except Exception:
        pass
    return None


def fetch_full_text(doi: str, pmcid: str = "") -> tuple[str, str]:
    """Return (text, source) where source is 'xml', 'html', or 'abstract'."""
    xml = _fetch_epmc_xml(pmcid)
    if xml:
        return xml, "xml"

    html = _fetch_publisher_html(doi)
    if html:
        return html, "html"

    return "", "abstract"


# ---------------------------------------------------------------------------
# Claude API evaluation
# ---------------------------------------------------------------------------

# The tool schema matches the output JSON format from the v2 prompt
EVALUATION_TOOL = {
    "name": "submit_evaluation",
    "description": (
        "Submit a structured evaluation of the paper. "
        "Set include=true only if quality_score >= 3."
    ),
    "input_schema": {
        "type": "object",
        "required": ["include", "quality_score"],
        "properties": {
            "include": {
                "type": "boolean",
                "description": "Whether this paper should be included (score >= 3)",
            },
            "exclusion_reason": {
                "type": "string",
                "description": "Brief reason for exclusion (if include=false)",
            },
            "quality_score": {
                "type": "number",
                "description": "Quality score 1.0-5.0",
            },
            "title": {"type": "string"},
            "first_author": {"type": "string"},
            "journal": {"type": "string"},
            "journal_tier": {"type": "integer", "enum": [1, 2]},
            "pub_date": {
                "type": "string",
                "description": "YYYY-MM-DD format",
            },
            "doi": {"type": "string"},
            "url": {"type": "string"},
            "dataset_repository": {
                "type": "array",
                "items": {"type": "string"},
            },
            "dataset_accession": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "repository": {"type": "string"},
                        "accession": {"type": "string"},
                        "description": {"type": "string"},
                        "role": {
                            "type": "string",
                            "enum": ["primary", "reanalyzed_key", "reanalyzed"],
                            "description": "primary = generated by this paper; reanalyzed_key = from another study but essential to main results; reanalyzed = minor comparison only",
                        },
                    },
                },
            },
            "num_datasets": {"type": "integer"},
            "estimated_processed_data_size_gb": {"type": "number"},
            "data_modality": {
                "type": "array",
                "items": {"type": "string"},
            },
            "modality_tier": {"type": "integer", "enum": [1, 2]},
            "domain": {"type": "string"},
            "domain_tags": {
                "type": "array",
                "items": {"type": "string"},
            },
            "hypothesis_chain": {
                "type": "object",
                "properties": {
                    "summary": {"type": "string"},
                    "steps": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "step_number": {"type": "integer"},
                                "description": {"type": "string"},
                                "computational": {"type": "boolean"},
                                "data_source": {"type": "string"},
                            },
                        },
                    },
                    "chain_type": {
                        "type": "string",
                        "enum": [
                            "entirely_computational",
                            "mostly_computational",
                            "mixed",
                        ],
                    },
                    "num_computational_steps": {"type": "integer"},
                    "reproducibility_pct": {"type": "integer"},
                },
            },
            "final_conclusion": {"type": "string"},
            "figures_from_dataset": {
                "type": "object",
                "properties": {
                    "dataset_figures": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                    "total_main_figures": {"type": "integer"},
                    "fraction": {"type": "number"},
                },
            },
            "code_available": {
                "type": "string",
                "enum": ["yes", "no", "partial"],
            },
            "code_url": {"type": "string"},
            "validation_dataset": {"type": "string"},
            "open_access_license": {"type": "string"},
            "notes": {"type": "string"},
        },
    },
}


def _build_user_message(paper: dict, full_text: str, text_source: str) -> str:
    """Build the user-message content for the evaluation call."""
    parts = [
        f"## Paper metadata",
        f"**Title:** {paper.get('title', 'N/A')}",
        f"**Authors:** {paper.get('authors', 'N/A')}",
        f"**Journal:** {paper.get('journal', 'N/A')} (tier {paper.get('journal_tier', '?')})",
        f"**DOI:** {paper.get('doi', 'N/A')}",
        f"**Published:** {paper.get('pub_date', 'N/A')}",
        f"**Open access:** {paper.get('is_open_access', 'N/A')}",
        f"**License:** {paper.get('license', 'N/A')}",
        "",
    ]

    if paper.get("abstract"):
        parts.append(f"## Abstract\n{paper['abstract']}\n")

    if full_text:
        parts.append(f"## Full text (source: {text_source})\n{full_text}\n")
    else:
        parts.append(
            "## Full text\nFull text could not be retrieved. "
            "Evaluate based on the abstract only. "
            "If the abstract alone does not provide enough information "
            "to confidently score ≥3, set include=false.\n"
        )

    parts.append(
        "## Instructions\n"
        "Evaluate this paper against the criteria. Use the submit_evaluation tool "
        "to return your assessment. Search the text for accession numbers "
        "(GSE*, PRJNA*, Zenodo, etc.), identify the hypothesis chain, "
        "count which figures come from deposited data, and score accordingly."
    )

    return "\n".join(parts)


def evaluate_single_paper(
    client: Anthropic,
    paper: dict,
) -> dict | None:
    """Evaluate one paper via the Claude API. Returns paper dict or None."""
    cfg = get_config()
    doi = paper.get("doi", "unknown")
    log.info("Evaluating: %s (%s)", doi, paper.get("title", "")[:60])

    # Fetch full text
    full_text, text_source = fetch_full_text(doi, paper.get("pmcid", ""))

    user_msg = _build_user_message(paper, full_text, text_source)

    try:
        response = client.messages.create(
            model=cfg.pipeline.model,
            max_tokens=cfg.evaluation.max_tokens,
            system=cfg.evaluation.system_prompt,
            messages=[{"role": "user", "content": user_msg}],
            tools=[EVALUATION_TOOL],
            tool_choice={"type": "tool", "name": "submit_evaluation"},
        )
    except Exception:
        log.exception("Claude API call failed for %s", doi)
        return None

    # Extract tool use result
    for block in response.content:
        if block.type == "tool_use" and block.name == "submit_evaluation":
            result = block.input
            if not result.get("include", False):
                log.info(
                    "Excluded: %s — %s (score %.1f)",
                    doi,
                    result.get("exclusion_reason", "no reason"),
                    result.get("quality_score", 0),
                )
                return None

            # Ensure standard fields are populated from metadata
            result.setdefault("doi", paper.get("doi", ""))
            result.setdefault("url", f"https://doi.org/{paper.get('doi', '')}")
            result.setdefault("title", paper.get("title", ""))
            result.setdefault("journal", paper.get("journal", ""))
            result.setdefault("journal_tier", paper.get("journal_tier", 1))
            result.setdefault("pub_date", paper.get("pub_date", ""))
            result.setdefault("first_author", paper.get("first_author", ""))
            result.setdefault("open_access_license", paper.get("license", ""))

            log.info("Included: %s — score %.1f", doi, result.get("quality_score", 0))
            return result

    log.warning("No tool_use block in response for %s", doi)
    return None


def evaluate_papers(
    candidates: list[dict],
) -> list[dict]:
    """Evaluate a batch of candidate papers in parallel.

    Returns list of paper dicts that passed evaluation (score >= 3).
    """
    cfg = get_config()
    max_workers = cfg.parallelism.eval_workers
    client = Anthropic()
    results: list[dict] = []

    with ThreadPoolExecutor(max_workers=max_workers) as pool:
        futures = {}
        for i, paper in enumerate(candidates):
            # Stagger submissions to respect rate limits
            if i > 0 and i % max_workers == 0:
                time.sleep(cfg.rate_limits.claude_api_delay * max_workers)
            fut = pool.submit(evaluate_single_paper, client, paper)
            futures[fut] = paper.get("doi", f"unknown_{i}")

        for fut in as_completed(futures):
            doi = futures[fut]
            try:
                result = fut.result()
                if result is not None:
                    results.append(result)
            except Exception:
                log.exception("Evaluation failed for %s", doi)

    log.info("Evaluation complete: %d/%d papers included", len(results), len(candidates))
    return results
