"""Step 7: Upload datasets to Edison and generate probe run.yaml files.

After uploading, creates a probe directory per paper with only run.yaml
(description.txt and objective.txt are generated by the probe generation pipeline):
    probes/<name>/
        run.yaml          — data_entry URI + run config
"""

import logging
import re
import subprocess
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from kosmos_pipeline.config import DOWNLOAD_WORKERS

log = logging.getLogger(__name__)

DEFAULT_KOSMOS_OPT_DIR = Path.home() / "kosmos-opt"

RUN_YAML_TEMPLATE = """\
data_entry: "{data_entry}"
primary_objective: objective.txt
dataset_description: description.txt
num_steps: 20
stage: {stage}
run_tardigrade: false

kosmos_config:
  enable_literature_research: false
"""


def upload_to_edison(
    data_dir: Path,
    name: str,
    stage: str = "DEV",
    kosmos_opt_dir: Path = DEFAULT_KOSMOS_OPT_DIR,
) -> str:
    """Upload a single dataset to Edison.

    Runs: python -m kopt.probe.upload <data_dir> --name <name> --stage <stage>
    Returns the full stdout from the upload command.
    """
    if not data_dir.exists():
        raise FileNotFoundError(f"Data directory not found: {data_dir}")

    if not kosmos_opt_dir.exists():
        raise FileNotFoundError(
            f"kosmos-opt directory not found: {kosmos_opt_dir}. "
            "Clone the repo or set --kosmos-opt-dir."
        )

    cmd = [
        "python", "-m", "kopt.probe.upload",
        str(data_dir),
        "--name", name,
        "--stage", stage,
    ]

    log.info("Uploading %s to Edison (stage=%s): %s", name, stage, " ".join(cmd))

    result = subprocess.run(
        cmd,
        cwd=str(kosmos_opt_dir),
        capture_output=True,
        text=True,
        timeout=600,
    )

    if result.returncode != 0:
        log.error("Upload failed for %s:\nstdout: %s\nstderr: %s", name, result.stdout, result.stderr)
        raise RuntimeError(f"Edison upload failed for {name}: {result.stderr}")

    log.info("Upload complete for %s: %s", name, result.stdout.strip()[:200])
    return result.stdout


def _parse_data_entry(stdout: str) -> str:
    """Extract the data_entry URI (e.g. data_entry:6aa009d5-...) from upload output."""
    match = re.search(r'(data_entry:[0-9a-f-]{36})', stdout)
    if match:
        return match.group(1)
    match = re.search(r'([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})', stdout)
    if match:
        return f"data_entry:{match.group(1)}"
    lines = [l.strip() for l in stdout.strip().splitlines() if l.strip()]
    return lines[-1] if lines else ""


def _get_probe_name(paper: dict) -> str:
    """Determine the probe directory name from paper accessions."""
    for acc in paper.get("dataset_accession", []):
        a = acc.get("accession", "")
        if a.upper().startswith("GSE"):
            return a.upper()
        if "zenodo" in a.lower():
            match = re.search(r'(\d{5,})', a)
            if match:
                return f"Zenodo_{match.group(1)}"
    return re.sub(r'[^\w.-]', '_', paper.get("doi", "unknown"))


def upload_all(
    papers: list[dict],
    datasets_dir: Path,
    probes_dir: Path,
    stage: str = "DEV",
    kosmos_opt_dir: Path = DEFAULT_KOSMOS_OPT_DIR,
) -> dict:
    """Upload all downloaded datasets to Edison and write run.yaml per paper.

    Args:
        papers: List of selected paper dicts.
        datasets_dir: Where downloaded data lives (datasets/<doi_safe>/).
        probes_dir: Where to write probe directories (probes/<name>/).
        stage: Edison environment stage.
        kosmos_opt_dir: Path to kosmos-opt repo.

    Returns:
        Dict mapping DOI → upload result with data_entry URI.
    """
    probes_dir.mkdir(parents=True, exist_ok=True)
    results = {}

    def _process_paper(paper: dict) -> tuple[str, dict]:
        """Upload a single paper's dataset and write its run.yaml."""
        doi = paper.get("doi", "unknown")
        doi_safe = re.sub(r'[^\w.-]', '_', doi)
        paper_data_dir = datasets_dir / doi_safe
        name = _get_probe_name(paper)

        if not paper_data_dir.exists():
            log.warning("No downloaded data for %s — skipping upload", doi)
            return doi, {"status": "skipped_no_data", "name": name}

        try:
            stdout = upload_to_edison(
                paper_data_dir, name, stage=stage, kosmos_opt_dir=kosmos_opt_dir
            )
            data_entry = _parse_data_entry(stdout)

            # Write run.yaml only — other probe files come from probe generation pipeline
            probe_dir = probes_dir / name
            probe_dir.mkdir(parents=True, exist_ok=True)
            run_yaml = RUN_YAML_TEMPLATE.format(data_entry=data_entry, stage=stage)
            (probe_dir / "run.yaml").write_text(run_yaml)
            log.info("Wrote %s/run.yaml (data_entry: %s)", probe_dir.name, data_entry)

            return doi, {
                "status": "uploaded",
                "name": name,
                "data_entry": data_entry,
                "probe_dir": str(probe_dir),
                "stdout": stdout.strip(),
            }
        except Exception as e:
            log.exception("Upload failed for %s", doi)
            return doi, {"status": "failed", "name": name, "error": str(e)}

    with ThreadPoolExecutor(max_workers=DOWNLOAD_WORKERS) as executor:
        futures = {
            executor.submit(_process_paper, paper): paper
            for paper in papers
        }
        for future in as_completed(futures):
            doi, result = future.result()
            results[doi] = result

    return results
